AGMInventorySystemWebApp/Areas/Approver1/Controllers/POController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AGMInventorySystemWebApp.Areas.Approver1.Controllers
{
    [Authorize(Roles = "Admin,Approver1")]
    public class POController : Controller
    {
        // GET: Approver1/PO
        public ActionResult Index()
        {
            return View();
        }

        // GET: Approver1/PO/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Approver1/PO/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Approver1/PO/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Approver1/PO/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Approver1/PO/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Approver1/PO/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Approver1/PO/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AGMInventorySystemWebApp/Areas/Approver1/Controllers/ShipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AGMInventorySystemWebApp.Areas.Approver1.Controllers
{
    [Authorize(Roles = "Admin,Approver1")]
    public class ShipmentController : Controller
    {
        // GET: Approver1/Shipment
        public ActionResult Index()
        {
            return View();
        }

        // GET: Approver1/Shipment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Approver1/Shipment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Approver1/Shipment/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Approver1/Shipment/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Approver1/Shipment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Approver1/Shipment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Approver1/Shipment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AGMInventorySystemWebApp/Areas/Approver1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ระบบลงทะเบียนชาวไร่ยาสูบ : Burley Registration System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")

    @Styles.Render("~/bundles/dataTablescss")
    @Scripts.Render("~/bundles/dataTablesjs")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#"><img src="~/Images/stec-bar.png" width="130" height="30" class="d-inline-block align-top" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home",new { Area = "" })"><i class="fa fa-Home"></i> Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home")"><i class="fa fa-Home"></i> Main Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "PO")"><i class="fa fa-shopping-cart"></i> PO</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Shipment")"><i class="fa fa-truck"></i> Shipment</a>
                    </li>
                </ul>
                @Html.Partial("~/Views/Shared/_LoginPartial.cshtml")
            </div>
        </div>
    </div>

    <div class="container body-content" style="margin-top:10px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - STEC BU Web Application.</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>